### ISSUE TITLE
Fetching external energy supply info

### ISSUE THREAD

**Issue by Jorilx** [erijo/sunnyportal-py#1]
Hi!
I was wondering if the web services at com.sunny-portal.de have some way to return the "external energy supply" info. I could try to write a patch if they do.
Thanks!

**Comment by erijo** [comment]
Can you see this info in the sunnyportal app or on the sunnyportal website?

**Comment by Jorilx** [comment]
From sunnyportal.com yes, from the app no, I can see only "Plant properties", "Plant profile" and "Yield"

**Comment by erijo** [comment]
I see. As I don't have that myself I can't really help you find the api. Try running the test client and see if you can find anything in the different responses that could point you to the api to use.

Alternative if you could give me access to you plant on sunnyportal (e.g. by adding me as a user) I could have a look and see if I can get anything out of it.

**Comment by erijo** [comment]
Closing this due to lack of reply.
