### ISSUE TITLE
"Sunny Portal e-mail" error with cron

### ISSUE THREAD

**Issue by bstrin** [erijo/sunnyportal-py#10]
Great work and thanks for making this available to use.

I got it working, but when executing using cron, I get an error that says only "Sunny Portal e-mail:" when logging cron output >> /var/log/cron.log
Prior to this, I had been getting the "no MTA" error so I installed postfix in local only mode. Just guessing these are tied together and the error I'm having now means it can't send the message out to the recorded "Sunny Portal e-mail" from the config file. Maybe?

I'm wondering if/how it could be made to not require the email, assuming that would take care of it.

**Comment by erijo** [comment]
Run the script manually first to create the config file. Then use the same config file when you run the script from cron.

**Comment by bstrin** [comment]
Thanks Erik. I forgot to specify the full path to the config file in the cron job. 

Now if sunny portal would stay updated every 15 minutes, everything would be perfect.
