### ISSUE TITLE
ModuleNotFound error with sunnyportal2file

### ISSUE THREAD

**Issue by antonyuhlmann** [erijo/sunnyportal-py#15]
Hi all
I'm trying to use sunnyportal2file but i get this error. I haven't touched at the packages nor the _init_.py

File "bin/sunnyportal2pvoutput", line 26, in <module>
import sunnyportal.client, sunnyportal.responses
ModuleNotFoundError: No module named 'sunnyportal'

Thanks in advance

**Comment by erijo** [comment]
Please see the README. You need to set `PYTHONPATH` to the directory where the module is (i.e. the current directory): `PYTHONPATH=. ./bin/sunnyportal2file -h`
