### ISSUE TITLE
<enhancement> add optional "days-past" argument to sunnyportal2pvoutput

### ISSUE THREAD

**Issue by michaelpeeters** [erijo/sunnyportal-py#16]
Hi, my Inverter is on an unreliable internet connection, so the updates to sunnyportal are not always available in the night. 
By adding an optional "days-past" argument I can update pvoutput with data of a previous date once sunnyportal is updated. 

eg: 
`PYTHONPATH=. ./bin/sunnyportal2pvoutput --status --days-past 1 sunnyportal.config` will fetch the productiondata from today and yesterday.

**Comment by erijo** [comment]
Closing this as #17 has been merged.
