### ISSUE TITLE
pvoutput deprecated addbatchoutput

### ISSUE THREAD

**Issue by jwillemsen** [erijo/sunnyportal-py#22]
I found recently that pvoutput has deprecated the addbatchoutput API, batching is now part of addoutput, but batching is only available for donations mode, see https://github.com/jwillemsen/saj_collector/issues/34. It looks this project needs to be updated because it uses addbatchoutput.jsp as far as I can tell.

**Comment by erijo** [comment]
Thanks for the info. I'll have a look at it.

**Comment by halfagascan** [comment]
any update on this?
thanks

**Comment by erijo** [comment]
Sorry, I forgot about this. Should be fixed now, please try it and let me know if it doesn't work.
