### ISSUE TITLE
Generate signature param

### ISSUE THREAD

**Issue by fernandolfc1983** [erijo/sunnyportal-py#27]
There is a parameter called "signature", how is it generated?

sig = hmac.new(self.token.key.encode(), digestmod=hashlib.sha1)
sig.update(self.method.lower().encode())
sig.update(self.service.lower().encode())

ts = self.get_timestamp(self.token.server_offset)
sig.update(ts.encode())
params["timestamp"] = ts

sig.update(self.token.identifier.lower().encode())

params["signature-method"] = "auth"
params["signature-version"] = self.version
params["token"] = self.token
params["signature"] = base64.standard_b64encode(sig.digest())  <-Here!

I don't program in python, I would like you to help me understand, there is a key when authenticating with email and password, but this part is confusing to me, it has sha1 and base64, can you clarify?

**Comment by erijo** [comment]
It's a standard [HMAC](https://en.wikipedia.org/wiki/HMAC) using SHA1 as the hash function. The resulting digest is then base64 encoded before being sent.
