### ISSUE TITLE
Does this work for EnnesOX?

### ISSUE THREAD

**Issue by ZooBear** [erijo/sunnyportal-py#28]
I've been playing around with this repo (great work btw), and I have an SMA account connected to the ordinary SMA portal, as well as their new EnnesOX platform. The script only manages to find the sunny portal sites. 

According to the SMA API website (below), EnnesOX is supported by the API?
https://developer.sma.de/sma-apis.html

Would be great to know if this repo can access EnnesOX account!

**Comment by erijo** [comment]
I don't know anything about the ennexOS platform so I'm afraid I can't answer the question. But in general, if it works in the Android app it should work with the code in sunnyportal-py.
