### ISSUE TITLE
 how is the power being captured within the responses script?

### ISSUE THREAD

**Issue by joelmaykon94** [erijo/sunnyportal-py#3]
I could not understand how you are doing the request to capture the power with the method DayOverviewResponse (OverviewResponse)

> `DayOverviewResponse(OverviewResponse)`

**Comment by erijo** [comment]
I'm not sure I understand the question.

If you want to see how to use the day overview, see e.g. [bin/sunnyportal2pvoutput](https://github.com/erijo/sunnyportal-py/blob/master/bin/sunnyportal2pvoutput#L194).

**Comment by joelmaykon94** [comment]
I want to get other values ​​and I do not understand how you do no responses, how is the request built for the sunny system, did you get some javascript from the system or HTML?

how did you find: 

> `tag = self.find_or_raise(tag, 'overview-day-fifteen-total')`


I need to look for other information in the system

**Comment by erijo** [comment]
I've analyzed the traffic between the app and the server.

**Comment by rhuygen** [comment]
Could you give a little more detail in how you do that?

**Comment by erijo** [comment]
It was a long time since I did this, but I think I used an SSL proxy and redirected the traffic there to have it captured in a decrypted form.

**Comment by joelmaykon94** [comment]
I resolved with the lib Requests in the python
thanks for atention the questions the github

*Atenciosamente,*

*Joel Maykon,*
*Graduando Analista de SIstema e bolsista desenvolvedor do CCSL IFRN-CNAT*


Em qua, 3 de abr de 2019 às 17:07, Erik Johansson <notifications@github.com>
escreveu:

**Comment by rhuygen** [comment]
> It was a long time since I did this, but I think I used an SSL proxy and redirected the traffic there to have it captured in a decrypted form.

oké, thanks, I'll try that...
