### ISSUE TITLE
Can plant.day_overview also show consumption? 

### ISSUE THREAD

**Issue by TUmans** [erijo/sunnyportal-py#31]
Question as in title. 
Can day_overview also capture data about consumption, battery charging, discharging, etc...?

Basically : all the info you see in the "energy balance" for each day (see graph below)
The generation info is already there, but the other information is missing.

![Github_Graph](https://user-images.githubusercontent.com/32844581/159581256-4e210991-2b16-46b6-aaac-d0e389098e9d.PNG)

And yes, I used "day_overview" with True for "include all".

As a side question : where did you find the documentation about the service you are using? Like a manual or something...

**Comment by erijo** [comment]
If the app can show it then it can probably be added. You'll have to dig through the app, maybe use a ssl mitm proxy and see what info you can find on their homepage. That's what I've done.

**Comment by erijo** [comment]
The sunnyportal API has been shut down.
