### ISSUE TITLE
Feature Request: Export all data to local file

### ISSUE THREAD

**Issue by tobiasboecker** [erijo/sunnyportal-py#35]
Well, thanks a lot for your tiny tool to export the logged data to a local file. Due to my lack of python dev know how I'd like to ask if you could just add a complete export of all retrieved data. In my use case I like to know how much energy per hour (kwh) from grid was used - just to calculate my dynamic power contract (tibber hourly). Thanks so much!

**Comment by erijo** [comment]
The sunnyportal API has been shut down.
