### ISSUE TITLE
HTTP 410 GONE error while logging

### ISSUE THREAD

**Issue by fungiboletus** [erijo/sunnyportal-py#36]
It looks like the API is not available anymore since a few hours.

It returns the HTTP error 410 GONE when trying to login.

**Comment by petepall** [comment]
The sunny portal dashboard is saying the interface is deprecated and thus it seems to have been taken off-line

![image](https://user-images.githubusercontent.com/42099752/206211690-4557d20d-63e8-4aa1-af8c-012b090b7900.png)

**Comment by sweh** [comment]
So that means the project is dead? Are there any alternatives?

**Comment by fungiboletus** [comment]
You have the official API now, with swagger/OpenAPI specifications. The main challenge is to get some API key, but it can be done and this is what I use now.

**Comment by petepall** [comment]
Been chasing SMA already for more than a month to get a key to switch but no response from them.

**Comment by fungiboletus** [comment]
You may want to check the laws about reverse engineering in your juridiction. In my case I can mention that the official Android application uses a public key. You can analyse the network traffic or decompile the apk to find it.

**Comment by sajonasra** [comment]
@fungiboletus so There is another way than purchasingthe API key for minimum 12€? That would be the only way I see at the moment.

https://developer.sma.de/api-plans.html
