### ISSUE TITLE
I have two arrays on the same plant, can I get the data for each array separately?

### ISSUE THREAD

**Issue by rhuygen** [erijo/sunnyportal-py#4]
Hi,

I have two arrays (SMA-7000 and SMA-3000) at the same plant. Currently your request client interface returns the summary for the plant. Is it possible to retrieve the values for the arrays separately? How would I have to change the request?

Thanks, Rik

**Comment by erijo** [comment]
I don't know of any way to do that unfortunately. At least not using this module. You could try [sma.py](https://github.com/erijo/energy-utils/blob/master/sma.py) which can talk directly to the inverters.

**Comment by rhuygen** [comment]
Great thanks!
