### ISSUE TITLE
API methods

### ISSUE THREAD

**Issue by bernatgaston** [erijo/sunnyportal-py#6]
Dear @erijo ,

Thanks for the amazing job you did. I am trying to adapt your code to be able to create a binding of openhab. The idea would be to create a python program that can be executed using openhab rules and items. Later on, I would like to create an opensource binding for sunnyportal.
However I am unable to find a documentation of the REST API used in your application. I would like to select different fields, I am specially interested in current production and current consumption. The first one can be obtained from the app, the second one only from the website (since it uses info from another device, the energy meter).
How was you knowing the methods of the com.sunnyportal.de API? Can you share with me?
Many thanks!

**Comment by erijo** [comment]
There is no documentation available that I know of. You'll have to resort to reverse engineering. 

I suggest you try the testclient (in bin). Enable the different API calls there and look in the output and see if what you're looking for is there. All info that's available in the app should be available here as well.

**Comment by bernatgaston** [comment]
Ok thanks!
